### ISSUE TITLE
README.md is misleading

### ISSUE THREAD

**Issue by ghost** [ventz/docker-openvpn#1]
The container isn't actually expecting anything in /data, in fact it specifically is *not* looking at /data but /etc/openvpn. /data is expected on the docker host, and only if you use the `-v` option exactly as it is at the bottom of the README. The existing wording could be confusing to people trying to map their OpenVPN configuration to /data inside the container instead of /etc/openvpn where it should be.

**Comment by ventz** [comment]
@nharward-hd Does it make more sense to you phrased as:

> Required "DATA" directory (on Docker server) for OpenVPN

> This container assumes you have a "/data" (or like) directory on your docker server with your OpenVPN server config and certs like so:
