### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by Blueforcer** [ventz/docker-openvpn#2]
is there any console output?
i configure my server but there are no logs for this container

**Comment by ventz** [comment]
@Blueforcer The logs are generated in the same dir as your `server.conf`

Example: 
```
certs  openvpn.log  openvpn-status.log  run.sh  server.conf
```

In this case, `openvpn.log` and `openvpn-status.log`

You will also have to make sure you are logging in your `server.conf`:
```
status openvpn-status.log
log         openvpn.log
log-append  openvpn.log
```
