### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by xiaoyang-connyun** [ventz/docker-openvpn#6]
I appreciate your contribution, and would like to use it in my work. However, I do not find any license here, could you please clarify a bit on this topic?

**Comment by ventz** [comment]
Hi Xiaoyang,

Thank you for reaching out to check.

Feel free to use it as needed (for both personal and commercial purposes), and if you can, please add attribution (name/url) — personally, I always do this for any open source projects, even if they don’t have any license requirements around it (MIT, Apache2, BSD, etc).

Good luck with your project, and I am glad you found this helpful.

**Comment by xiaoyang-connyun** [comment]
Thanks for your reply, I will definitely do that.

**Comment by xiaoyang-connyun** [comment]
Clarified.
